### PR TITLE
update MCM16 json template

### PR DESCRIPTION
**Pull request by attiladoor**
changes are mostly obtained by auto format
please first merge: https://github.com/contactless/wb-mqtt-serial/pull/55

### CODE REVIEW

**Comment by attiladoor** [comment]
From MIO version 1.4.1 there is no need for "single" template: https://github.com/evgeny-boger/modbus_peripherals_hw/pull/46

**Comment by evgeny-boger** [comment]
looks like you commented the wrong pull request

**Comment by evgeny-boger** [comment]
poll_interval must not be used in templates

**Comment by evgeny-boger** [comment]
have you tested the final version?

**Comment by attiladoor** [comment]
yes, it is tested

**Pull request merged**
