### PR TITLE
Feature/wbio ai template

### PR DESCRIPTION
**Pull request by attiladoor**

### CODE REVIEW

**Comment by attiladoor** [comment]
could you merge it, please?

**Comment by evgeny-boger** [comment]
1) please update debian version
2) is it tested?

**Comment by attiladoor** [comment]
Yes, i have tested. But here is one thing: these templates are only for AI-DV12 without jumpers, so maybe i should make 2 more for e.g.: WBIO-AI-DV-12-50V and: WBIO-AI-DV-12-50V-single with only the 6 differential channels. What do you think?

**Comment by evgeny-boger** [comment]
1) first of all, non-single version has never been released, so you can remove the corresponding templates.
2) yes, I think it's good idea to make 50V version templates

**Comment by evgeny-boger** [comment]
again, NON-SINGLE version have not been released. Only a single devices on a bus is supported at the moment

**Comment by attiladoor** [comment]
Actually, from MIO 1.4.1 https://github.com/evgeny-boger/modbus_peripherals_hw/pull/46 there is no need for SINGLE template

**Pull request closed without merging**
